### ISSUE TITLE
Improve usability of expanding sections on training page

### ISSUE THREAD

**Issue by smth** [okfn/services#1]
@noelmas do you have any more context from the feedback?

Suggestions:
- [x] Make trigger buttons viewable in old (pre media query support) versions of IE (https://github.com/okfn/services/commit/b282023524e72b7478df5924d940d529c3292e4a).
- [ ] Move the contact/register buttons to within the expanding panel, to eliminate choice of action.
- [ ] Make trigger button text more descriptive, i.e "Our Open Data Training Courses".

**Comment by noelmas** [comment]
Nothing more from me
