### ISSUE TITLE
Improve user experience when booking via Eventbrite

### ISSUE THREAD

**Issue by smth** [okfn/services#2]
The available options for the ideal solution of keeping the process within our site appear to be crude and limited. As the user will have to leave our site at some stage, I think the most useful thing we can do is just make it clear that the user is about to go to the third party site.

**Comment by adamamyl** [comment]
In the past, for Eventbrite, I've used [iframes](http://help.eventbrite.com/customer/portal/articles/428470-how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets) to keep people on the site.

Do we not want to do that?

**Comment by smth** [comment]
I looked at the ticket form iframe. It appears that as soon as you click order button you are taken to the Eventbrite website anyway. This doesn't improve usability in my mind, just slightly delays the problem. Unless we have another reason to resort to an iframe (there could be an argument for it increasing uptake), I'd rather avoid it.
